### PR TITLE
Fixes: CSS + Icon + New Settings

### PR DESCRIPTION
**Pull request by flavioislima**
## Features
- Added option to install/update DXVK on prefix #120 
- Added option to change Tray Icon Color #109 
- Updated Tray Icons
- Created CSS variables for the sake of consistency
- Add SVG icons from original Design
- Elements should scale now with the size of the window
- Images, logos, etc. are kept offline

## Bugfixes:
- Some CSS fixes due to translations

### CODE REVIEW

**Comment by flavioislima** [comment]
@D3SOX 
Hi!

Need translation to those two keys:
    "autodxvk": "Auto Install/Update DXVK on Prefix",
    "darktray": "Use Dark Tray Icon (needs restart)"

Thanks! :D

**Comment by D3SOX** [comment]
```
"autodxvk": "Automatisches Installieren/Aktualisieren von DXVK im Prefix",
"darktray": "Benutze Dunkles Taskleisten-Icon (benötigt Neustart)"
```

**Comment by CTRL-ALT-DEL-92** [comment]
> ## Features
> * Added option to install/update DXVK on prefix #120
> * Added option to change Tray Icon Color #109
> * Updated Tray Icons
> 
> ## Bugfixes:
> * Some CSS fixes due to translations



> @D3SOX
> Hi!
> 
> Need translation to those two keys:
> "autodxvk": "Auto Install/Update DXVK on Prefix",
> "darktray": "Use Dark Tray Icon (needs restart)"
> 
> Thanks! :D
Dear heroic developer, thanks for your amazing work. I'd like to propose a couple of new features for this project. The first is the possibility to use Crossover other than wine and proton, this feature would improve the experience especially for mac users. Second a mac build, Crossover mac users are enthusiast about your project but many of them claim that they haven't the skill to compile your program by themselves. If you consider to add this two features the entire crossover mac community will use your project, since epic games launcher is very buggy and a real pain to use on wine/crossover. I want to thank you again for your efforts and  wish you good luck with your work. You Rock!!!!!!!!

**Comment by flavioislima** [comment]
@onadrog can you send me the french translations to these as well?
```
"autodxvk": "Auto Install/Update DXVK on Prefix",
"darktray": "Use Dark Tray Icon (needs restart)"
```

**Comment by flavioislima** [comment]
@CTRL-ALT-DEL-92 send request on the issues here on the repo.
But a Mac version is impossible since there is no legendary for mac now and Heroic uses it to connect to the Epic games.

**Comment by onadrog** [comment]
@flavioislima  
```javascript
"autodxvk": "Installation/Mise à jour automatique du préfix DXVK",
"darktray": "Utiliser Dark Tray Icon (nécessite un redémarrage)"
```
Et voilà.

**Pull request merged**
