### PR TITLE
Adding Hungarian Language

### PR DESCRIPTION
**Pull request by BiRo96**

### CODE REVIEW

**Comment by BiRo96** [comment]
Maybe there are still some conjugation and spelling mistakes, it was a little late, when I made these trabslations yesterday :)

**Comment by ianwijma** [comment]
No worries @BiRo96, let us know once you think its ready :+1:

**Comment by BiRo96** [comment]
I guess it's ready now, I hope I found all the mistakes I made and all the situations of the one-word transation texts that I misunderstood for the first time :D

**Comment by flavioislima** [comment]
> I guess it's ready now @ianwijma, I hope I found all the mistakes I made and all the situations of the one-word transation texts that I misunderstood for the first time :D

Hi! Thanks for that, man!
One question: is this your primary language? :D

**Comment by BiRo96** [comment]
> > I guess it's ready now @ianwijma, I hope I found all the mistakes I made and all the situations of the one-word transation texts that I misunderstood for the first time :D
> 
> Hi! Thanks for that, man!
> One question: is this your primary language? :D
> also, can you add screenshots?

Hi!
Yes it is :)
It was a pleasure to translate this project. 
I was searching a working and easy way to get my epic games on linux, for a long time. And I felt like I need to help on this, even if it's only to translate it.

Here are the screenshots
image
image
image

The only thing I couldn't find in translation resource files are these words on sync options and sync button
image

**Comment by flavioislima** [comment]
Nice!

Yes, about that list o forgot to add the labels, at the time.
But anyway, be ready to be our official Hungarian translator now. Once we need new translation we will ping you on some Pull request here on github. 

Also, do not forget to enter our discord server to discuss further improvements on the Heroic. 😁

**Review by flavioislima — APPROVED** [review]

**Pull request merged**
