### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by D3SOX**
I am a native German speaker and I created translations for Heroic.
If you need more strings in the future, you can contact me :smiley: 

You probably have to adjust some CSS there:
a
b

### CODE REVIEW

**Comment by tomuser123** [comment]
I've got a few suggestion. :)
https://github.com/tomuser123/HeroicGamesLauncher/commit/3af13234dc626752a14cb8ad0af5c4673937eb5f

**Comment by D3SOX** [comment]
@tomuser123  Thanks, I'll add them to this PR

**Comment by D3SOX** [comment]
You also had some typos in there (f.e. `forfahren`, `Feheler` and the formal `Sie`/`Ihre` should always be capitalized) so I didn't cherry-pick your commits but there should be everything included now :smiley:

**Review by flavioislima — APPROVED** [review]
Amazing Job, man! And was really fast! 😮 
thanks a lot!

It will be available on the next release.

**Comment by flavioislima** [comment]
Let me know when it is ready to be merged :)

**Comment by flavioislima** [comment]
> You probably have to adjust some CSS there:
> a
> b

This definitely needs to be improved. I'll check

**Comment by D3SOX** [comment]
> Let me know when it is ready to be merged :)

Except for the CSS issues it's ready 👍

**Pull request merged**
